<a href="https://colab.research.google.com/github/Malu-Freitas/Malu-Freitas/blob/main/cria%C3%A7ao_de_arrays_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CRIANDO ARRAYS UNIDIMENSIONAIS**

**sintaxe**: vetor = numpy.array([valor1, valor2, valorn])

Um par de colchetes somente representa uma única linha, onde as colunas e seus elementos são separados por vírgulas.

In [ ]:
import numpy as np # importação do numpy com alias

vetor = np.array([1, 1, 1])
print(f'Vetor criado: {vetor}')

Vetor criado: [1 1 1]


# **CRIANDO ARRAYS BIDIMENSIONAIS (LINHA E COLUNA)**

**sintaxe**: vetor = numpy.array([  ],[  ])

Cada par de colchetes                              internos representa uma linha, onde seus elementos de coluna são separados por vírgula


In [1]:
import numpy as np

matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Matriz 3 X 3:\n {matriz}')




Matriz 3 X 3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# **CRIANDO ARRAYS COM TODOS OS ELEMENTOS 0**

Sintaxe: array = numpy.zeros([linhas, colunas])

Deve-se passar a dimensão do array.
Uma dimensão será um vetor.
Duas dimensões será uma matriz.

In [ ]:
import numpy as np

vetor = np.zeros(5) # uma dimensão não precisa de colchetes
print(f'Vetor de 5 elementos zero: {vetor}')

matriz = np.zeros([2, 2])
print(f'Matriz 2 X 2 de elementos zero: \n {matriz}')

Vetor de 5 elementos zero: [0. 0. 0. 0. 0.]
Matriz 2 X 2 de elementos zero: 
 [[0. 0.]
 [0. 0.]]


# **CRIANDO ARRAYS COM TODOS OS ELEMENTOS 1**

Sintaxe: array = numpy.ones([linhas, colunas])

Deve-se passar a dimensão do array.
Uma dimensão será um vetor.
Duas dimensões será uma matriz.

In [ ]:
import numpy as np

vetor = np.ones(3) # uma dimensão não precisa de colchetes
print(f'Vetor de 3 elementos um: {vetor}')

matriz = np.ones([3, 3])
print(f'Matriz 3 X 3 de elementos um: \n {matriz}')

Vetor de 3 elementos um: [1. 1. 1.]
Matriz 3 X 3 de elementos um: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# **CRIANDO MATRIZ IDENTIDADE**

Sintaxe: array = numpy.eyes(dimensão)

Deve-se passar a dimensão da matriz, que por ser identidade é sempre uma matriz quadrada.

In [ ]:
import numpy as np

matrizI = np.eye(3)
print(f'Matriz Identidade 3 X 3:\n {matrizI}')


Matriz Identidade 3 X 3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# **CRIANDO MATRIZ COM DIAGONAL PRINCIPAL FORMADA POR UM ÚNICO VALOR E OS OUTROS ELEMENTOS IGUAL A ZERO**

**Sintaxe**: matriz = numpy.diag([valor])

**Nota**: a quantidade de valores da diagonal principal dará a dimensão da matriz (sempre quadrada)



In [ ]:
import numpy as np

D = np.diag([10, 10, 10]) # três valores, a matriz será 3 X 3
print('D = \n', D)


D = 
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


# **USANDO ARANGE PARA CRIAR VETORES**

**Sintaxe**: array = numpy.arange(inicio, fim, passo)

**Nota**: o valor indicado no fim nunca entra no arranjo.

In [ ]:
import numpy as np

vetor0 = np.arange(20)
print(f'Vetor com passo 1: {vetor0}')

vetor1 = np.arange(1, 10)
print(f'Vetor com passo 1: {vetor1}')

vetor2 = np.arange(1, 20, 2)
print(f'Vetor com passo 2: {vetor2}')

Vetor com passo 1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Vetor com passo 1: [1 2 3 4 5 6 7 8 9]
Vetor com passo 2: [ 1  3  5  7  9 11 13 15 17 19]


# **CRIANDO ARRAYS UNIDIMENSIONAIS COM LINSPACE**

**Sintaxe**: array = numpy.linspace(inicio, fim, quantidade de elementos)

**Nota**: o passO é criado automaticamente para gerar a quantidade necessária.

In [ ]:
import numpy as np

vetor3 = np.linspace(1, 10, 10)
print(f'Vetor com passo e qtde indicada: {vetor3}')

Vetor com passo e qtde indicada: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


# **USANDO VSTACK E HSTACK PARA CRIAR ARRAYS**

**VSTACK**


**Sintaxe**: array = numpy.vstack((array1, array2))

Adiciona elementos de um ou mais array na vertical. Os arrays tem q ter o mesmo número de colunas.

**HSTACK**

**Sintaxe**: array = numpy.hstack((array1, array2))

Adiciona elementos de um ou mais array na horizontal. Os arrays tem q ter o mesmo número de linhas.

In [ ]:
import numpy as np

# usando vstack
A = np.array([[1, 2],[3, 4],[5, 6]])
B = np.array([[7, 8],[9, 10]])

V = np.vstack((A, B))
print(f'Matrizes A e B unidas na vertical:\n{V}\n')

# usando hstack
C = np.zeros(3)
D = np.ones(3)

H = np.hstack((C, D))
print(f'Matrizes C e D unidas na horizontal:\n{H}\n')

Matrizes A e B unidas na vertical:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

Matrizes C e D unidas na horizontal:
[0. 0. 0. 1. 1. 1.]



# **LENDO DADOS PELO TECLADO PARA UM VETOR**

In [ ]:
import numpy as np
vetor = np.array(range(5)) * 0

for i in range(0, len(vetor)):
  vetor[i] = int(input(f'Digite o elemento {i} do vetor: '))

print(f'Vetor lido: {vetor}')

Digite o elemento 0 do vetor: 1
Digite o elemento 1 do vetor: 2
Digite o elemento 2 do vetor: 3
Digite o elemento 3 do vetor: 4
Digite o elemento 4 do vetor: 5
Vetor lido: [1 2 3 4 5]


# **LENDO DADOS PELO TECLADO PARA UMA MATRIZ**

In [ ]:
import numpy as np

#matriz = np.array(range(9)).reshape(3,3) * 0
matriz = np.zeros([3, 3])

for i in range(0, 3): # caminhando por linhas
  for j in range (0, 3): # caminhando por colunas
    matriz[i][j] = int(input(f'Digite o elemento {i}{j} da matriz: '))

print(matriz)

Digite o elemento 00 da matriz: 1
Digite o elemento 01 da matriz: 2
Digite o elemento 02 da matriz: 3
Digite o elemento 10 da matriz: 4
Digite o elemento 11 da matriz: 5
Digite o elemento 12 da matriz: 6
Digite o elemento 20 da matriz: 7
Digite o elemento 21 da matriz: 8
Digite o elemento 22 da matriz: 9
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
